### Consulta todos as movimentações do produto
POST http://localhost/pdv/reports/stockHandling
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productCode": 100,
  "type": [1,2,3,4,5],
  "startDate": "2019-12-14T03:00:00.000Z",
  "endDate": "2021-12-14T03:00:00.000Z"
}